" Remap keys in normal, visual, and operator-pending modes
" nnoremap l h
" nnoremap ; l
" nnoremap h b
"
" onoremap l h
" onoremap ; l
" onoremap h b

nnoremap gh _
nnoremap gl $
vnoremap gh _
vnoremap gl $

xnoremap gh _
xnoremap gl $

onoremap gh _
onoremap gl $
