#!/bin/sh

# Function to start a program in the background if it exists
start() {
    if command -v "$1" > /dev/null 2>&1; then
        # Check if the program is already running
        if ! pidof -sx "$1" &> /dev/null; then
            "$@" &
            echo "Started: $*" >> ~/xinit.log
        else
            echo "Already running: $*" >> ~/xinit.log
        fi
    else
        echo "Executable not found: $1" >> ~/xinit.log
    fi
}

# Set DPI and other settings
start xrandr --dpi 100

safe_start xkeyboard
safe_start alacritty
safe_start dim-screen dark
safe_start chromium


# Uncomment to start additional services or applications
# start pulseaudio --start
# start google-chrome-stable

exec $WM_EXEC
